global:
  scrape_interval: 15s

scrape_configs:

  # FastAPI - Data Processing
  - job_name: 'IoT-aws-data-processing'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'data_processing:9558'

  # Telegraf - Data Ingestion
  - job_name: 'IoT-azure-data-ingestion'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'telegraf:9273'

  # Grafana - Azure
  - job_name: 'IoT-azure-data-visualizing'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'grafana_sec:3333'

  # Grafana - AWS
  - job_name: 'IoT-aws-data-visualizing'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'grafana_app:3000'