name: Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1


      - name: Validar EC2
        run: |
          aws cloudformation validate-template \
            --template-body file://infrastructure/cloudformation/01-ec2.yaml

      - name: Validar SSM
        run: |
          aws cloudformation validate-template \
            --template-body file://infrastructure/cloudformation/02-session-manager.yaml

      - name: Obter Instance Profile
        id: profile
        run: |
          PROFILE=$(aws iam list-instance-profiles-for-role \
            --role-name LabRole \
            --query 'InstanceProfiles[0].InstanceProfileName' \
            --output text)
          echo "profile=$PROFILE" >> "$GITHUB_OUTPUT"

      - name: Obter VPC_ID
        id: vpc
        run: |

          VPC_ID=$(aws cloudformation describe-stacks \
            --stack-name G6-vpc \
            --query "Stacks[0].Outputs[?OutputKey=='VpcId'].OutputValue" \
            --output text)

          echo "VPC_ID encontrado: $VPC_ID"

          if [ -z "$VPC_ID" ] || [ "$VPC_ID" = "None" ]; then
            echo "ERRO: VPC_ID não encontrado."
            exit 1
          fi

          echo "vpc_id=$VPC_ID" >> "$GITHUB_OUTPUT"

      - name: Obter SUBNET_ID
        id: subnet
        run: |

          SUBNET_ID=$(aws cloudformation describe-stacks \
            --stack-name G6-network \
            --query "Stacks[0].Outputs[?OutputKey=='PublicSubnetId'].OutputValue" \
            --output text)

          echo "SUBNET_ID encontrado: $SUBNET_ID"

          if [ -z "$SUBNET_ID" ] || [ "$SUBNET_ID" = "None" ]; then
            echo "ERRO: SUBNET_ID não encontrado."
            exit 1
          fi

          echo "subnet_id=$SUBNET_ID" >> "$GITHUB_OUTPUT"

      - name: Deploy EC2
        run: |
          aws cloudformation deploy \
            --stack-name data-viz-ec2 \
            --template-file infrastructure/cloudformation/01-ec2.yaml \
            --region us-east-1 \
            --parameter-overrides \
              LabInstanceProfile=${{ steps.profile.outputs.profile }} \
              SubnetId=${{ steps.subnet.outputs.subnet_id }} \
              VpcId=${{ steps.vpc.outputs.vpc_id }} \
              InstanceType=t3.small # Pode mudar